import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/index.scss";
import Provider from "../context";
import { Sidebar } from "../index";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["300","400","500","600","700"], // Add the weights you need
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Provider>
            <html lang="en">
                <body className={poppins.className}>
                    <Sidebar />
                    <div className="main-content">{children}</div>
                </body>
            </html>
        </Provider>
    );
}
